var mongoose = require('mongoose');

var EventSchema = new mongoose.Schema({
    address:{type:String},
    city:{type:String},
    closingTime:{type:String},
    dateRange:{type:Array},
    description:{type:String},
    earlyBird:{type:Boolean},
    earlyBirdAvailableTickets:{type:String},
    earlyBirdDelivery:{type:Array},
    earlyBirdFree:{type:Boolean},
    earlyBirdPaymentMode:{type:Array},
    earlyBirdPrice:{type:String},
    earlyBirdTotalTickets:{type:String},
    email:{type:String},
    eventCategory:{type:String},
    eventTitle:{type:String},
    faceBook:{type:String},
    google:{type:String},
    images:{type:Array},
    linkdIn:{type:String},
    name:{type:String},
    normalTicket:{type:Boolean},
    normalTicketAvailableTickets:{type:String},
    normalTicketDelivery:{type:Array},
    normalTicketFree:{type:Boolean},
    normalTicketPaymentMode:{type:Array},
    normalTicketPrice:{type:String},
    normalTicketTotalTickets:{type:String},
    number:{type:String},
    objectId:{type:String},
    openingTime:{type:String},
    posted:{type:String},
    profileId:{type:String},
    randomKey:{type:String},
    state:{type:String},
    userId:{type:String},
    website:{type:String},   
    bannerSrc:{ type:String },
    coverPhotoSrc:{type:String},
    top:{type:String},
    termsCondition:{type:Array},
    map:{type:Boolean},
    customTicketDetail:{type:Array}
});

mongoose.model('EventSchema',EventSchema);
